model_name = "lightonai/LightOnOCR-2-1B"
ocr_instruction = "Write the text as flowing paragraphs, in which you join hyphenated words at line breaks, and only preserve only actual paragraph breaks. Ignore text formatting like italics. Only output the text itself, do not comment at all."
default_input_file = 'input.jpg'
default_input_folder = 'input'
print_limit = 1800
separator = '\n\n---\n'
image_extensions = ('.jpg', '.jpeg', '.png', '.bmp', '.gif', '.tiff', '.tif', '.webp')
default_input_pdf = 'input.pdf'
pdf_dpi = 300
